### ISSUE TITLE
The connection string 'mongodb://MONGO_INITDB_ROOT_USERNAME:MONGO_INITDB_ROOT_PASSWORD@:27000' is not valid.

### ISSUE THREAD

**Issue by binarychen** [microsoft/SmartKG#65]
smartkg_services-smartkg-1     | Application startup exception: MongoDB.Driver.MongoConfigurationException: The connection string 'mongodb://MONGO_INITDB_ROOT_USERNAME:MONGO_INITDB_ROOT_PASSWORD@:27000' is not valid.
smartkg_services-smartkg-1     |    at MongoDB.Driver.Core.Configuration.ConnectionString.Parse()
smartkg_services-smartkg-1     |    at MongoDB.Driver.Core.Configuration.ConnectionString..ctor(String connectionString)
smartkg_services-smartkg-1     |    at MongoDB.Driver.MongoUrlBuilder.Parse(String url)
smartkg_services-smartkg-1     |    at MongoDB.Driver.MongoUrl..ctor(String url)
smartkg_services-smartkg-1     |    at SmartKG.Common.DataPersistance.MongoDataAccessor..ctor(String connectionString, String mgmtDatabaseName) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataPersistance\MongoDataAccessor.cs:line 35
smartkg_services-smartkg-1     |    at SmartKG.Common.DataPersistence.DataLoader..ctor(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataPersistance\DataLoader.cs:line 48
smartkg_services-smartkg-1     |    at SmartKG.Common.DataStoreMgmt.DataStoreManager..ctor(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataStoreMgmt\DataStoreManager.cs:line 32
smartkg_services-smartkg-1     |    at SmartKG.Common.DataStoreMgmt.DataStoreManager.initInstance(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataStoreMgmt\DataStoreManager.cs:line 39
smartkg_services-smartkg-1     |    at SmartKG.KGBot.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ILogger`1 _log) in C:\Users\jull\source\github\SmartKG\src\SmartKG.KGBot\Startup.cs:line 56
smartkg_services-smartkg-1     | --- End of stack trace from previous location where exception was thrown ---
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
smartkg_services-smartkg-1     | crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
smartkg_services-smartkg-1     |       Application startup exception
smartkg_services-smartkg-1     | MongoDB.Driver.MongoConfigurationException: The connection string 'mongodb://MONGO_INITDB_ROOT_USERNAME:MONGO_INITDB_ROOT_PASSWORD@:27000' is not valid.
smartkg_services-smartkg-1     |    at MongoDB.Driver.Core.Configuration.ConnectionString.Parse()
smartkg_services-smartkg-1     |    at MongoDB.Driver.Core.Configuration.ConnectionString..ctor(String connectionString)
smartkg_services-smartkg-1     |    at MongoDB.Driver.MongoUrlBuilder.Parse(String url)
smartkg_services-smartkg-1     |    at MongoDB.Driver.MongoUrl..ctor(String url)
smartkg_services-smartkg-1     |    at SmartKG.Common.DataPersistance.MongoDataAccessor..ctor(String connectionString, String mgmtDatabaseName) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataPersistance\MongoDataAccessor.cs:line 35
smartkg_services-smartkg-1     |    at SmartKG.Common.DataPersistence.DataLoader..ctor(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataPersistance\DataLoader.cs:line 48
smartkg_services-smartkg-1     |    at SmartKG.Common.DataStoreMgmt.DataStoreManager..ctor(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataStoreMgmt\DataStoreManager.cs:line 32
smartkg_services-smartkg-1     |    at SmartKG.Common.DataStoreMgmt.DataStoreManager.initInstance(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataStoreMgmt\DataStoreManager.cs:line 39
smartkg_services-smartkg-1     |    at SmartKG.KGBot.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ILogger`1 _log) in C:\Users\jull\source\github\SmartKG\src\SmartKG.KGBot\Startup.cs:line 56
smartkg_services-smartkg-1     | --- End of stack trace from previous location where exception was thrown ---
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
smartkg_services-smartkg-1     |
smartkg_services-smartkg-1     | Unhandled Exception: MongoDB.Driver.MongoConfigurationException: The connection string 'mongodb://MONGO_INITDB_ROOT_USERNAME:MONGO_INITDB_ROOT_PASSWORD@:27000' is not valid.
smartkg_services-smartkg-1     |    at MongoDB.Driver.Core.Configuration.ConnectionString.Parse()
smartkg_services-smartkg-1     |    at MongoDB.Driver.Core.Configuration.ConnectionString..ctor(String connectionString)
smartkg_services-smartkg-1     |    at MongoDB.Driver.MongoUrlBuilder.Parse(String url)
smartkg_services-smartkg-1     |    at MongoDB.Driver.MongoUrl..ctor(String url)
smartkg_services-smartkg-1     |    at SmartKG.Common.DataPersistance.MongoDataAccessor..ctor(String connectionString, String mgmtDatabaseName) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataPersistance\MongoDataAccessor.cs:line 35
smartkg_services-smartkg-1     |    at SmartKG.Common.DataPersistence.DataLoader..ctor(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataPersistance\DataLoader.cs:line 48
smartkg_services-smartkg-1     |    at SmartKG.Common.DataStoreMgmt.DataStoreManager..ctor(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataStoreMgmt\DataStoreManager.cs:line 32
smartkg_services-smartkg-1     |    at SmartKG.Common.DataStoreMgmt.DataStoreManager.initInstance(IConfiguration config) in C:\Users\jull\source\github\SmartKG\src\SmartKG.Common\DataStoreMgmt\DataStoreManager.cs:line 39
smartkg_services-smartkg-1     |    at SmartKG.KGBot.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ILogger`1 _log) in C:\Users\jull\source\github\SmartKG\src\SmartKG.KGBot\Startup.cs:line 56
smartkg_services-smartkg-1     | --- End of stack trace from previous location where exception was thrown ---
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
smartkg_services-smartkg-1     |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
smartkg_services-smartkg-1     |    at SmartKG.KGBot.Program.Main(String[] args) in C:\Users\jull\source\github\SmartKG\src\SmartKG.KGBot\Program.cs:line 14
smartkg_services-mongo-1 exited with code 1
smartkg_services-smartkg-1     | Aborted (core dumped)
smartkg_services-smartkg-1 exited with code 134

**Comment by binarychen** [comment]
The changes in docker-compose.yml and appsettings.json do not take effect.
![image](https://github.com/microsoft/SmartKG/assets/818576/66ff9c33-346f-436d-9642-213bde51a3e9)
![image](https://github.com/microsoft/SmartKG/assets/818576/d9413dc6-94df-4342-a5f2-91a11c52e9b3)
